name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  couscous:
    name: Deploy website with Couscous
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Couscous
        uses: CouscousPHP/GitHub-Action@v1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.couscous/generated
